version: "2.1"

orbs:
  circleci-cli: circleci/circleci-cli@0.1.1

executors:
  default:
    docker:
      - image: circleci/buildpack-deps

commands:
  test_orb:
    parameters:
      orb_file:
        type: string
    steps:
      - checkout
      - run:
          name: Validate hello-orb.yml
          command: circleci orb validate << parameters.orb_file >>

jobs:
  test_hello:
    executor: default
    steps:
      - circleci-cli/install
      - test_orb:
          orb_file: hello-orb.yml

workflows:
  commit:
    jobs:
      - test_hello
