version: "2.1"

orbs:
  orb-tools: circleci/orb-tools@2.0.2

workflows:
  commit:
    jobs:
      - orb-tools/test-in-builds:
          orb-location: src/hello-world/orb.yml
          orb-name: hello-world
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: src/hello-world/test.yml
