version: "2.1"

orbs:
  orb-tools: circleci/orb-tools@2.0.2

workflows:
  commit:
    jobs:
      - orb-tools/test-in-builds:
          orb-location: hello-orb.yml
          orb-name: hello-orb
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: test/config.yml
