version: "2.1"

executors:
  circleci:
    docker:
      - image: circleci/buildpack-deps

commands:
  test_orb:
    parameters:
      orb_file:
        type: string
    steps:
      - checkout
      - run:
          name: Validate hello-orb.yml
          command: circleci orb validate << parameters.orb_file >>

jobs:
  test_hello:
    executor: circleci
    steps:
      - test_orb:
          orb_file: hello-orb.yml

workflows:
  commit:
    jobs:
      - test_hello
