version: "2.1"

orbs:
  orb-tools: circleci/orb-tools@2.0.2
  slack: circleci/slack@0.1.1

executors:
  default:
    docker:
      - image: circleci/buildpack-deps

jobs:
  send-approval-link:
    executor: default
    steps:
      - slack/notify:
          message: |
            Please check and approve Job to deploy.
            https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}

workflows:
  version: "2"

  build_test_deploy:
    jobs:
      - orb-tools/test-in-builds:
          orb-location: src/hello-world/orb.yml
          orb-name: hello-world
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: src/hello-world/test.yml

      - orb-tools/publish:
          requires:
            - orb-tools/test-in-builds
          filters:
            branches:
              ignore: master
          orb-path: src/hello-world/orb.yml
          orb-ref: tsub/hello-world@dev:${CIRCLE_BRANCH}
          publish-token-variable: "$ORB_PUBLISHING_TOKEN"

      - send-approval-link:
          requires:
            - orb-tools/test-in-builds
          filters:
            branches:
              only: master

      - manual-approval:
          type: approval
          requires:
            - send-approval-link
          filters:
            branches:
              only: master

      - orb-tools/increment:
          requires:
            - manual-approval
          filters:
            branches:
              only: master
          orb-path: src/hello-world/orb.yml
          orb-ref: tsub/hello-world
          segment: patch
          publish-token-variable: "$ORB_PUBLISHING_TOKEN"
