version: "2.1"

orbs:
  orb-tools: circleci/orb-tools@2.0.2

workflows:
  build_test_deploy:
    jobs:
      - orb-tools/test-in-builds:
          orb-location: src/hello-world/orb.yml
          orb-name: hello-world
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: src/hello-world/test.yml

      - orb-tools/publish:
          requires:
            - orb-tools/test-in-builds
          filters:
            branches:
              ignore: master
          orb-path: src/hello-world/orb.yml
          orb-ref: tsub/hello-world@dev:${CIRCLE_BRANCH}
          publish-token-variable: "$ORB_PUBLISHING_TOKEN"

      - orb-tools/increment:
          requires:
            - orb-tools/test-in-builds
          filters:
            branches:
              only: master
          orb-path: src/hello-world/orb.yml
          orb-ref: tsub/hello-world
          segment: patch
          publish-token-variable: "$ORB_PUBLISHING_TOKEN"
